### ISSUE TITLE
Import Error with htmlReport in k6-reporter v3.0.0 and v3.0.1

### ISSUE THREAD

**Issue by Subramanyamveeraiah** [benc-uk/k6-reporter#79]
After upgrading to k6-reporter v3.0.0 and v3.0.1, importing htmlReport in my k6 script throws an error:

`SyntaxError: https://raw.githubusercontent.com/benc-uk/k6-reporter/3.0.1/dist/bundle.js: Unexpected token (1:84563)`

The same script works fine with version v2.4.0. and lower versions, It seems the module export format changed in v3.x, causing incompatibility with k6

**Error message**
`k6 run test.js
ERRO[0002] SyntaxError: https://raw.githubusercontent.com/benc-uk/k6-reporter/3.0.0/dist/bundle.js: Unexpected token (1:83146)
> 1 | var e={557:e=>{e.exports=function e(t,n,a){function i(r,c){if(!n[r]){if(!t[r]){if(s)return s(r,!0);var o=new Error("Cannot find module '"+r+"'");throw o.code="MODULE_NOT_FOUND",o}var l=n[r]={exports:{}};t[r][0].call(l.exports,function(e){return i(t[r][1][e]||e)},l,l.exports,e,t,n,a)}return n[r].exports}for(var s=void 0,r=0;r<a.length;r++)i(a[r]);return i}({1:[function(e,t,n){var a=e("fs"),i=e("path"),s=e("./utils"),r=!1,c=e("../package.json").version,o="locals",l=

**Comment by benc-uk** [comment]
What version of k6 are you on?

The bundle is fully compatible with k6

**Comment by benc-uk** [comment]
<img width="1044" height="803" alt="Image" src="https://github.com/user-attachments/assets/bcd40adc-a71f-4927-8410-3d41fc978b62" />

**Comment by benc-uk** [comment]
Thank you for confirming, and this is useful, I'll update the readme so people are aware of this too
